# Generated by Django 4.0.1 on 2022-01-10 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('other', 'Новая'), ('phones', 'Телефоны'), ('TVs', 'Телевизоры'), ('notebooks', 'Ноутбуки')], default='other', max_length=11, verbose_name='Категория')),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Остаток')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
            ],
        ),
    ]
